name: Train and Deploy Recommender Models

on:
  # This runs the job automatically every day at 5:30 AM UTC
  schedule:
    - cron: '30 5 * * *'
  # This also allows you to run it manually from the Actions tab on GitHub
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt

      - name: Run training script
        run: python train.py
        env:
          # These secrets must be configured in your GitHub repo settings
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }}
          TMDB_API_TOKEN: ${{ secrets.TMDB_API_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPO: ${{ secrets.GITHUB_REPO }}